from enum import Enum


class Status(Enum):
    ABORT = "MISSION ABORTED"
    VERIFIED = "STATUS VERIFIED"
    NOT_VERIFIED = "STATUS NOT VERIFIED"
    MANUAL = "MANUAL LOG INVOKED"
    RESET = "VARIABLES RESET"
    RESTART = "PROGRAM RESTART"
    LAUNCHED = "LAUNCHED"
